apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tyk-sre-golang
  labels:
    app: tyk-sre-golang
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - nonResourceURLs: ["/version"]
    verbs: ["get"]
