apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyk-sre-golang
  labels:
    app: tyk-sre-golang
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tyk-sre-golang
  template:
    metadata:
      labels:
        app: tyk-sre-golang
    spec:
      serviceAccountName: tyk-sre-golang
      containers:
        - name: tyk-sre-golang
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
